In [22]:
# from google.colab import drive
# drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
#importation des bibliothéque 
import statsmodels.formula.api as s
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix,accuracy_score
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import datetime
#importation base de donnée
# df = pd.read_csv('/content/drive/MyDrive/stageASM/dataset.csv',header=None)

df = pd.read_csv('dataset.csv')

In [5]:
df

                          ART_Designation  price         ddm  qte
0                  EAU M. SAFIA 1.5L /QT6   0.60  31/12/2021    2
1                 FLEURE B30 SANS FEUILLE   4.80  31/12/2021    1
2         CAKE TODAY SNOWBALL  24P /CT144   0.70  31/12/2021    1
3                  CIRAGE VILO CREME 60ML   2.15  31/12/2021    1
4               THON BIBENE 400G HV /CT24   6.20  31/12/2021    2
...                                   ...    ...         ...  ...
1048570                  GAUFRETTE LINGOT   1.60  20/10/2021    1
1048571        BISCUIT MAXON 6P CACAO 55G   0.90  20/10/2021    2
1048572          CHOCOLAT LOVE DRAGE 80GR   1.20  20/10/2021    1
1048573  CAKE DONUT TODAY BLUE BERRY 45G    0.65  20/10/2021    1
1048574             SERPILLIERE COTON 505   7.50  20/10/2021    1

[1048575 rows x 4 columns]

In [26]:
df[df['ART_Designation']== "SERPILLIERE COTON 505"]

               ART_Designation  price         ddm  qte
967146   SERPILLIERE COTON 505    7.5  26/06/2021    1
983157   SERPILLIERE COTON 505    7.5  25/06/2021    1
994012   SERPILLIERE COTON 505    7.5  24/10/2021    1
1048574  SERPILLIERE COTON 505    7.5  20/10/2021    1

In [24]:
# effacer les quantités négatives 
df = df[df[1]> 0].reset_index(drop = True)
# effacer les prix négatives 
df = df[df[3]> 0].reset_index(drop = True)

In [25]:
#df=df.shift(1)
#df=df.iloc[1:]

In [ ]:
#dtypes of all the columns
df.info()
#number of unique rows in each feature
df.nunique().sort_values()
#the stats of all the columns
display(df.describe())

In [28]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df[0] = le.fit_transform(df[0])

In [ ]:
import datetime as dt
t = pd.to_datetime(df[2])
r=t.map(dt.datetime.toordinal)
df['r']=r
df['r']

In [32]:
a=df[0].unique()

In [33]:
b=df[2].unique()
l=[]
for i in b :
   df1=df[df[2]==i]
   l.append(df1[0])

In [ ]:
#!pip install scikit-learn

In [41]:
x=df[[0,'r']].values
y=df[1].values
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1)

In [42]:
reg=LinearRegression()
reg.fit(x_train,y_train)
print ( reg. intercept_ ) 
print ( reg. coef_ )

5841.663297733076
[ 0.09263369 -0.00790097]

In [43]:
#Here x.values will have only values without headers
y_pred=reg.predict(x_test)

In [45]:
import datetime as dt
s='01-09-2022'
r=dt.datetime.toordinal(pd.to_datetime(s))
df1=df[df[0]==26]
print(df1[1])
reg.predict([[26,r]])

9       1.00
23      5.01
86     10.01
125    10.02
147     4.98
163     2.00
173    10.04
187     5.02
191     1.00
201     2.00
211     5.07
234     2.00
248     5.04
260     9.96
276     1.00
287     4.99
Name: 1, dtype: float64

array([11.85727882])

In [46]:
reg_df=pd.DataFrame()
reg_df['originale']=y_test
reg_df['Predictions']=y_pred
reg_df

    originale  Predictions
0       10.11     9.928329
1       15.11     9.967834
2        1.00    11.382409
3       20.05     9.577141
4        3.00    10.303776
5        1.00     8.978845
6        1.00     7.786609
7        5.02     8.642903
8        2.00    11.455696
9        6.68    10.357716
10      15.20     9.086725
11       5.04     9.254012
12       1.00    11.366607
13       2.00    10.364806
14       1.00    10.576209
15      20.15     9.944131
16       2.00    10.766944
17       5.06     8.820270
18       2.00    11.064192
19      30.02     7.775719
20      10.07     8.824626
21      16.00    10.932054
22      20.15     8.650804
23       1.00    10.641340
24       5.02    10.129144
25       1.00    10.633439
26      10.10     9.750963
27       5.03     9.722904
28      20.09     8.635002
29      15.77     7.312551

In [47]:
w=reg.score(x_train,y_train)
print(w)

0.007278918406469215

In [17]:
from sklearn.metrics import *
print('MAE:',mean_absolute_error(y_test,y_pred))
print('MSE:',mean_squared_error(y_test,y_pred))
print('RMSE:',np.sqrt(mean_squared_error(y_test,y_pred)))

MAE: 8.506010917969414
MSE: 236.8050504716983
RMSE: 15.388471349412791

In [ ]:
plt.scatter(x_test[0],y_test,label='y')
plt.scatter(x_test[0],y_pred,alpha=0.8,label='y')

In [ ]:
from sklearn.model_selection import cross_val_score
#cross_val_score(LinearRegression(),x_test,y_test,cv=3,scoring='accuracy')

In [ ]:
pip install mlxtend

In [ ]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder

In [ ]:
te = TransactionEncoder()
te_ary = te.fit(l).transform(l)
te_ary

array([[False,  True, False, ...,  True,  True, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ...,  True, False, False],
       ...,
       [False,  True,  True, ...,  True,  True, False],
       [ True, False,  True, ...,  True,  True, False],
       [False, False, False, ..., False, False, False]])

In [ ]:
te_ary.astype("int")

In [ ]:
te.columns_

In [ ]:
df=pd.DataFrame(te_ary, columns=te.columns_)
df

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,False,True,False,False,False,False,True,True,False,True,...,False,False,False,False,True,False,True,True,True,False
1,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
5,False,False,True,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,True,False,False
6,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
7,True,False,True,True,False,False,False,False,False,False,...,False,True,False,False,False,False,False,True,True,False
8,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,True,True,False,False,True,False,False,False,...,False,False,False,True,False,True,False,True,False,False
10,False,False,False,True,True,True,False,False,False,True,...,False,False,False,True,False,False,False,True,False,False
11,True,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,True,False,True,False,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
13,True,False,True,True,False,True,True,False,False,False,...,False,False,True,True,True,False,False,True,False,False
14,True,False,False,True,True,True,False,False,False,False,...,False,True,False,True,False,False,False,True,True,False
15,False,False,False,True,False,True,True,False,False,False,...,False,False,False,True,False,False,False,True,False,False
16,True,False,False,False,True,True,False,False,False,False,...,False,False,False,True,False,False,False,True,True,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,True,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
19,False,False,False,True,False,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
20,True,False,True,True,True,True,True,False,False,False,...,False,False,False,True,True,False,False,True,False,False
21,True,False,False,True,True,True,True,False,False,False,...,False,False,False,True,False,True,False,True,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
23,True,False,True,False,False,False,False,False,False,True,...,True,False,False,True,True,False,False,True,True,False
24,True,False,True,True,False,True,False,False,False,True,...,False,False,False,True,True,False,False,True,True,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,True
26,False,False,True,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
27,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,True,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
30,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
31,True,False,True,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
32,True,False,True,False,True,False,True,False,False,True,...,True,False,False,False,False,False,False,True,True,False
33,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
35,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,True,True,False
37,True,False,True,True,False,False,True,False,False,False,...,False,False,False,True,True,False,False,True,False,False
38,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
39,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
40,True,False,True,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
41,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
42,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
43,False,True,True,False,False,False,False,True,False,False,...,False,False,False,True,True,False,True,True,True,False
44,True,False,True,True,False,False,True,False,True,False,...,False,False,False,False,True,False,False,True,True,False
45,False,False,False,False,False,False,False,False,False,True,...,True,False,False,True,False,False,False,False,False,False

In [ ]:
from mlxtend.frequent_patterns import apriori

In [ ]:
frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
frequent_itemsets

    support itemsets
0  0.673913     (29)

In [ ]:
from mlxtend.frequent_patterns import association_rules

In [ ]:
res = association_rules(frequent_itemsets,metric="confidence",min_threshold=0.7)
res

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction]
Index: []

In [ ]:
res1=res[['antecedents','consequents','support','confidence','lift']]
res1

Empty DataFrame
Columns: [antecedents, consequents, support, confidence, lift]
Index: []

In [ ]:
res2=res1[res1['confidence'] >= 1]
res2

Empty DataFrame
Columns: [antecedents, consequents, support, confidence, lift]
Index: []